### PR TITLE
Modernize for new plugin API for 0.92.0

### PR DESCRIPTION
**Pull request by devyn**
I think this works reasonably well. I think I might patch it further so you don't have to provide the plugin name, and it just comes from the project name. 

Annoying that `--force` is required for underscores.

### CODE REVIEW

**Comment by fdncred** [comment]
ya, let's give it a try! thanks.

**Comment by fdncred** [comment]
ok, here's some feedback after running it.

1. we want to enforce the project to be called nu_plugin_\<input or command\>. we probably need to restore this functionality. maybe you're right, that it could/should be inferred?
2. the readme probably needs to be updated.
3. the main.rs could be tweaked a little. there's an impl with new() that is kind of unnecessary if you change the main() to just reference the plugin name.
4. really, i'd just like there to be 1 rust file if it's a simple plugin and maybe 2 (or 3) if it's not simple. i just want it to be as approachable as possible. sometimes rust's module system is confusing for me.
5. i'd like repository to be in the cargo.toml because it's helpful if published to crates.io. it can just be a bogus url if we don't want to capture it somehow.


This is how my first plugin with it went.
❯ cargo generate --git https://github.com/fdncred/nu_plugin_template --force
🤷   Project Name: my_test
🔧   Destination: /Users/fdncred/src/my_test ... <-- expected this to be nu_plugin_my_test
🔧   project-name: my_test ... <-- and this to be nu_plugin_my_test
🔧   Generating template ...
🤷   What is the name of this plugin package? (will automatically be prefixed by nu_plugin_): some_test
🤷   What should your first command be called? (spaces are okay): some_test
✔ 🤷   Would you like a simple command? Say no if you would like to use streaming. · Yes
🔧   Moving generated files into: `/Users/fdncred/src/my_test`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/fdncred/src/my_test

**Comment by devyn** [comment]
@fdncred 

> ok, here's some feedback after running it.
> 
>     1. we want to enforce the project to be called nu_plugin_<input or command>. we probably need to restore this functionality. maybe you're right, that it could/should be inferred?

Yeah, I wish there was a way we could tell cargo-generate that we want to decide the crate name for them. Then we could just generate it based on their plugin name.

But I think as it is I can just warn them if their crate name doesn't match the pattern it should 

>     2. the readme probably needs to be updated.

Yup

>     3. the main.rs could be tweaked a little. there's an impl with new() that is kind of unnecessary if you change the main() to just reference the plugin name.

Yeah, I definitely prefer this, but I was sort of thinking it might make it easier if you did want to add state. But I guess anyone that advanced will already know how to do it, so maybe I'll just leave it out.

>     4. really, i'd just like there to be 1 rust file if it's a simple plugin and maybe 2 (or 3) if it's not simple. i just want it to be as approachable as possible. sometimes rust's module system is confusing for me.

I could add a question about whether they intend to create more than one command 

>     5. i'd like repository to be in the cargo.toml because it's helpful if published to crates.io. it can just be a bogus url if we don't want to capture it somehow.

Okay, how about we ask for their GitHub username and just leave the repo field blank if they don't enter it

**Comment by fdncred** [comment]
> Yeah, I wish there was a way we could tell cargo-generate that we want to decide the crate name for them. Then we could just generate it based on their plugin name.

I think we just prompt them for the crate name and say it will be appended to nu_plugin_

> I could add a question about whether they intend to create more than one command

That's fine too. Or maybe we have a simple template and a streaming template?

> Okay, how about we ask for their GitHub username and just leave the repo field blank if they don't enter it

That's fine.

When it's all said and done, I just want people to be able to create a plugin from this, compile it, and register it, and it work before they put any code into it. Then they can start tweaking and changing things to their style. I know this template has helped me write a bunch of plugins and it's good to just get the boilerplate out of the way.

**Comment by devyn** [comment]
> I think we just prompt them for the crate name and say it will be appended to nu_plugin_

Unfortunately the project name stuff is handled by cargo-generate itself, and I'm not sure if there's a way to override it. We don't generate that initial prompt. We can set the crate name in Cargo.toml to something else but that's about it. I can certainly force the crate name to match the `nu_plugin_` pattern though, and warn them if their project directory name isn't going to match it.

**Comment by fdncred** [comment]
> and I'm not sure if there's a way to override it

prior to your changes, that's how it worked. you supply a name and it's named nu_plugin_name.

maybe i'm mixing up terms/nomenclature. i just mean what the folder (nu_plugin_name) is called and what the plugin binary is compiled to (nu_plugin_name).

**Pull request merged**
